### ISSUE TITLE
Warning error

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-html-optimization#5]
Hi!

I see the following log entries with the current version:

`PHP message: PHP Warning: preg_match() expects at least 2 parameters, 1 given in /var/www/*/web/wp/wp-content/plugins/wordpress-html-optimization/controllers/html.class.php on line 634`

**Comment by optimalisatie** [comment]
Thanks a lot for reporting the issue! 

It was a bug related to the CDN filter of the Image and Link Optimization tools that excludes links like `javascript` and `tel:`. The issue has been fixed in the latest update.

### CDN mask

Did you know about the CDN mask feature? You can shorten CDN URLs by using a mask. For example, you could purchase a cheap short domain, e.g. `x.co`, and serve images on path `/wp-content/theme_name/images/` from `//i.x.co/image-name.jpg` (10 chars) instead of `//cdn.domain.com/wp-content/theme_name/images/image-name.jpg` (47 chars). When you have a page with many images then it could save HTML data transfer which is helpful for Google Lighthouse.

The CDN mask works very simple. It simply removes a part of the path on the assumption that the domain will serve from that location.

You can configure a mask using JSON. 

![image](https://user-images.githubusercontent.com/8843669/42772804-d66052aa-892b-11e8-8872-a13fb46ea215.png)
